'use client';

import React, { useState } from 'react';
import { useOffice } from '@/lib/OfficeContext';
import { FileText, Download, Loader2, CheckCircle, LayoutTemplate } from 'lucide-react';
import jsPDF from 'jspdf';

export function PitchDeckForge() {
    const { activeProject, activeRoom } = useOffice();
    const [isGenerating, setIsGenerating] = useState(false);
    const [isComplete, setIsComplete] = useState(false);

    const generatePDF = async () => {
        if (!activeProject) return;
        setIsGenerating(true);
        setIsComplete(false);

        // Simulate "Processing" time for effect
        await new Promise(r => setTimeout(r, 1500));

        const doc = new jsPDF({
            orientation: 'landscape',
            unit: 'mm',
            format: 'a4'
        });

        const bg = "#111111";
        const textLight = "#ffffff";
        const accent = "#0D9488";

        // Helper to add a slide
        const addSlide = (title: string, content: string | string[], notes: string = "") => {
            doc.addPage();
            doc.setFillColor(bg);
            doc.rect(0, 0, 297, 210, "F");

            // Header
            doc.setFontSize(24);
            doc.setTextColor(accent);
            doc.setFont("helvetica", "bold");
            doc.text(title.toUpperCase(), 20, 30);

            // Divider
            doc.setDrawColor(accent);
            doc.setLineWidth(0.5);
            doc.line(20, 35, 277, 35);

            // Content
            doc.setFontSize(14);
            doc.setTextColor(textLight);
            doc.setFont("helvetica", "normal");

            if (Array.isArray(content)) {
                let y = 50;
                content.forEach(line => {
                    const splitText = doc.splitTextToSize("• " + line, 250);
                    doc.text(splitText, 25, y);
                    y += (splitText.length * 7) + 5;
                });
            } else {
                const splitText = doc.splitTextToSize(content || "Content pending...", 250);
                doc.text(splitText, 25, 50);
            }

            // Footer
            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            doc.text(`${activeProject.name} | Confidential Information`, 20, 200);
        };

        // 1. Title Slide (Configured manually to be first page, overwrite default blank if needed)
        // jsPDF starts with 1 page. We'll paint over it.
        doc.setPage(1);
        doc.setFillColor(bg);
        doc.rect(0, 0, 297, 210, "F");

        doc.setFontSize(40);
        doc.setTextColor(textLight);
        doc.setFont("helvetica", "bold");
        doc.text(activeProject.name.toUpperCase(), 148.5, 90, { align: "center" });

        doc.setFontSize(16);
        doc.setTextColor(accent);
        doc.text("INVESTOR PRESENTATION", 148.5, 105, { align: "center" });

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by DeepChox C-Suite on ${new Date().toLocaleDateString()}`, 148.5, 180, { align: "center" });

        // 2. Problem
        addSlide("The Problem", activeProject.userNotes || "Define the core pain point here.");

        // 3. Solution
        addSlide("The Solution", activeProject.productPlan || "Describe your product intervention.");

        // 4. Market Opportunity
        addSlide("Market Opportunity", activeProject.marketInsights || "Analyze the TAM, SAM, and SOM.");

        // 5. Business Model
        addSlide("Business Model", activeProject.strategy || "Explain how you capture value.");

        // 6. Financials
        addSlide("Financial Overview", activeProject.budget || "Cost structure and revenue projections.");

        // 7. Team
        addSlide("The Team", activeProject.teamDirectives || "Key personnel and structure.");

        // Save
        doc.save(`${activeProject.name.replace(/\s+/g, '_')}_Pitch_Deck.pdf`);

        setIsGenerating(false);
        setIsComplete(true);
    };

    if (!activeProject) return <div className="p-10 text-zinc-500">No active project loaded.</div>;

    return (
        <div className="flex flex-col h-full bg-brand-bg text-brand-text items-center justify-center p-10">
            <div className="max-w-2xl w-full bg-zinc-900/30 border border-zinc-800 p-10 rounded-3xl text-center space-y-8 backdrop-blur-xl shadow-2xl">

                <div className="w-20 h-20 bg-zinc-900 rounded-2xl flex items-center justify-center mx-auto border border-zinc-800 shadow-xl">
                    <LayoutTemplate className="w-10 h-10 text-[#0D9488]" />
                </div>

                <div>
                    {activeRoom === 'cmo' && (
                        <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-zinc-500">
                            CMO · GTM plan or messaging framework
                        </p>
                    )}
                    <h2 className="text-3xl font-bold tracking-tight mb-2">
                        {activeRoom === 'cmo' ? 'Chief Marketing Officer' : 'Pitch Deck Forge'}
                    </h2>
                    <p className="text-zinc-500">
                        {activeRoom === 'cmo'
                            ? 'Shape narrative and motion — this forge turns venture intel into a slide story you can ship or rehearse.'
                            : 'Instantly compile your Strategy, Financials, and Market Intel into a professional 7-slide PDF investor presentation.'}
                    </p>
                </div>

                <div className="grid grid-cols-2 gap-4 text-left max-w-md mx-auto">
                    <div className="p-3 bg-zinc-950/50 rounded-lg border border-zinc-900">
                        <div className="text-[10px] uppercase text-zinc-600 font-bold">Slide 1</div>
                        <div className="text-sm font-bold text-zinc-300">Title & Vision</div>
                    </div>
                    <div className="p-3 bg-zinc-950/50 rounded-lg border border-zinc-900">
                        <div className="text-[10px] uppercase text-zinc-600 font-bold">Slide 2</div>
                        <div className="text-sm font-bold text-zinc-300">The Problem</div>
                    </div>
                    <div className="p-3 bg-zinc-950/50 rounded-lg border border-zinc-900">
                        <div className="text-[10px] uppercase text-zinc-600 font-bold">Slide 3</div>
                        <div className="text-sm font-bold text-zinc-300">The Solution</div>
                    </div>
                    <div className="p-3 bg-zinc-950/50 rounded-lg border border-zinc-900">
                        <div className="text-[10px] uppercase text-zinc-600 font-bold">Slide 4-7</div>
                        <div className="text-sm font-bold text-zinc-300">Market, Biz, $$$, Team</div>
                    </div>
                </div>

                <button
                    onClick={generatePDF}
                    disabled={isGenerating}
                    className="w-full py-4 bg-gradient-to-r from-[#0D9488] to-teal-700 hover:from-teal-500 hover:to-teal-600 text-white font-bold rounded-xl transition-all shadow-lg shadow-teal-900/20 active:scale-95 disabled:opacity-50 flex items-center justify-center gap-3"
                >
                    {isGenerating ? (
                        <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                            Forging Deck...
                        </>
                    ) : isComplete ? (
                        <>
                            <CheckCircle className="w-5 h-5" />
                            Deck Downloaded
                        </>
                    ) : (
                        <>
                            <Download className="w-5 h-5" />
                            Generate Pitch Deck
                        </>
                    )}
                </button>
            </div>
        </div>
    );
}
