'use client';

import React, { useState } from 'react';
import { useOffice } from '@/lib/OfficeContext';
import { Download, Loader2, CheckCircle, LayoutTemplate } from 'lucide-react';
import { DeskShell, DeskEmpty } from '@/components/workspaces/DeskShell';
import jsPDF from 'jspdf';

export function PitchDeckForge() {
    const { activeProject, activeRoom } = useOffice();
    const [isGenerating, setIsGenerating] = useState(false);
    const [isComplete, setIsComplete] = useState(false);

    const generatePDF = async () => {
        if (!activeProject) return;
        setIsGenerating(true);
        setIsComplete(false);

        // Simulate "Processing" time for effect
        await new Promise(r => setTimeout(r, 1500));

        const doc = new jsPDF({
            orientation: 'landscape',
            unit: 'mm',
            format: 'a4'
        });

        const bg = "#111111";
        const textLight = "#ffffff";
        const accent = "#0D9488";

        // Helper to add a slide
        const addSlide = (title: string, content: string | string[], notes: string = "") => {
            doc.addPage();
            doc.setFillColor(bg);
            doc.rect(0, 0, 297, 210, "F");

            // Header
            doc.setFontSize(24);
            doc.setTextColor(accent);
            doc.setFont("helvetica", "bold");
            doc.text(title.toUpperCase(), 20, 30);

            // Divider
            doc.setDrawColor(accent);
            doc.setLineWidth(0.5);
            doc.line(20, 35, 277, 35);

            // Content
            doc.setFontSize(14);
            doc.setTextColor(textLight);
            doc.setFont("helvetica", "normal");

            if (Array.isArray(content)) {
                let y = 50;
                content.forEach(line => {
                    const splitText = doc.splitTextToSize("• " + line, 250);
                    doc.text(splitText, 25, y);
                    y += (splitText.length * 7) + 5;
                });
            } else {
                const splitText = doc.splitTextToSize(content || "Content pending...", 250);
                doc.text(splitText, 25, 50);
            }

            // Footer
            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            doc.text(`${activeProject.name} | Confidential Information`, 20, 200);
        };

        // 1. Title Slide (Configured manually to be first page, overwrite default blank if needed)
        // jsPDF starts with 1 page. We'll paint over it.
        doc.setPage(1);
        doc.setFillColor(bg);
        doc.rect(0, 0, 297, 210, "F");

        doc.setFontSize(40);
        doc.setTextColor(textLight);
        doc.setFont("helvetica", "bold");
        doc.text(activeProject.name.toUpperCase(), 148.5, 90, { align: "center" });

        doc.setFontSize(16);
        doc.setTextColor(accent);
        doc.text("INVESTOR PRESENTATION", 148.5, 105, { align: "center" });

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by DeepChox C-Suite on ${new Date().toLocaleDateString()}`, 148.5, 180, { align: "center" });

        // 2. Problem
        addSlide("The Problem", activeProject.userNotes || "Define the core pain point here.");

        // 3. Solution
        addSlide("The Solution", activeProject.productPlan || "Describe your product intervention.");

        // 4. Market Opportunity
        addSlide("Market Opportunity", activeProject.marketInsights || "Analyze the TAM, SAM, and SOM.");

        // 5. Business Model
        addSlide("Business Model", activeProject.strategy || "Explain how you capture value.");

        // 6. Financials
        addSlide("Financial Overview", activeProject.budget || "Cost structure and revenue projections.");

        // 7. Team
        addSlide("The Team", activeProject.teamDirectives || "Key personnel and structure.");

        // Save
        doc.save(`${activeProject.name.replace(/\s+/g, '_')}_Pitch_Deck.pdf`);

        setIsGenerating(false);
        setIsComplete(true);
    };

    if (!activeProject) {
        return <DeskEmpty>No active project loaded.</DeskEmpty>;
    }

    const isCmo = activeRoom === 'cmo';

    return (
        <DeskShell
            eyebrow={isCmo ? 'CMO · GTM plan or messaging framework' : 'Pitch forge · Export'}
            title={isCmo ? 'Chief Marketing Officer' : 'Pitch Deck Forge'}
            description={
                isCmo
                    ? 'Shape narrative and motion — this forge turns venture intel into a slide story you can ship or rehearse.'
                    : 'Compile strategy, financials, and market intel into a seven-slide PDF investor deck.'
            }
        >
            <div className="mx-auto flex max-w-2xl flex-col items-center gap-8 py-4 text-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-xl border border-zinc-700 bg-zinc-900">
                    <LayoutTemplate className="h-8 w-8 text-zinc-400" aria-hidden />
                </div>

                <div className="grid max-w-md grid-cols-2 gap-3 text-left">
                    <div className="rounded-lg border border-zinc-700 bg-zinc-900/50 p-3">
                        <div className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Slide 1</div>
                        <div className="text-sm font-medium text-zinc-200">Title & vision</div>
                    </div>
                    <div className="rounded-lg border border-zinc-700 bg-zinc-900/50 p-3">
                        <div className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Slide 2</div>
                        <div className="text-sm font-medium text-zinc-200">The problem</div>
                    </div>
                    <div className="rounded-lg border border-zinc-700 bg-zinc-900/50 p-3">
                        <div className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Slide 3</div>
                        <div className="text-sm font-medium text-zinc-200">The solution</div>
                    </div>
                    <div className="rounded-lg border border-zinc-700 bg-zinc-900/50 p-3">
                        <div className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Slides 4–7</div>
                        <div className="text-sm font-medium text-zinc-200">Market, biz, money, team</div>
                    </div>
                </div>

                <button
                    type="button"
                    onClick={generatePDF}
                    disabled={isGenerating}
                    className="flex w-full max-w-md items-center justify-center gap-2 rounded-lg border border-zinc-600 bg-zinc-800 py-3.5 text-sm font-semibold text-zinc-100 shadow-md transition hover:bg-zinc-700 active:scale-[0.99] disabled:opacity-50"
                >
                    {isGenerating ? (
                        <>
                            <Loader2 className="h-5 w-5 animate-spin" aria-hidden />
                            Forging deck…
                        </>
                    ) : isComplete ? (
                        <>
                            <CheckCircle className="h-5 w-5" aria-hidden />
                            Deck downloaded
                        </>
                    ) : (
                        <>
                            <Download className="h-5 w-5" aria-hidden />
                            Generate pitch deck
                        </>
                    )}
                </button>
            </div>
        </DeskShell>
    );
}
